/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker can be customized! See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other code you'd like.
// You can also remove this file if you'd prefer not to use a service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching.
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html file.
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    }

    // If this is a URL that starts with /_,' then it's probably a non-navigation request
    // that we don't want to handle.
    if (url.pathname.startsWith('/_/')) {
      return false;
    }

    // Skip Clerk auth callback / task URLs so they always hit the network.
    // This prevents stale cached index.html from interfering with multi-step
    // sign-in flows (e.g. 2FA factor-two screens).
    if (url.hostname.includes('clerk')) {
      return false;
    }

    // If this is a URL that contains a file extension, skip this route.
    if (url.pathname.match(/\.[^/]*$/)) {
      return false;
    }

    // Return true to signal that we want to handle the request.
    return true;
  },
  // Serve the precached app shell for SPA navigations.
  createHandlerBoundToURL('/index.html'),
);

// An example runtime caching route for requests that aren't handled by the precache,
// using a Stale-While-Revalidate strategy. Set a custom expiration time.
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'),
  // Customize this strategy as needed, e.g., by changing the cache name.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  }),
);

// Cache CSS, JS, and JSON files with a CacheFirst strategy
registerRoute(
  ({ request }) =>
    request.destination === 'style' ||
    request.destination === 'script' ||
    request.destination === 'worker' ||
    request.destination === 'font' ||
    request.destination === 'image' ||
    request.url.endsWith('.json'),
  new CacheFirst({
    cacheName: 'static-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60,
      }), // 30 Days
    ],
  }),
);

// NOTE: API caching is intentionally disabled. API requests go to a
// cross-origin Workers domain (*.workers.dev) while the frontend is served
// from a different origin (*.pages.dev). StaleWhileRevalidate cannot handle
// opaque cross-origin responses, which causes "no-response" errors and CORS
// failures. All API data should be fetched fresh from the network.

// This allows the web app to trigger a skipWaiting revision for service worker updates
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.
